# Generated by Django 4.0.4 on 2022-04-18 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='image',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ImageField(upload_to='images')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_alternative', to='auctions.listing')),
            ],
        ),
    ]
